name       : yubikey-manager
version    : 0.6.0
release    : 9
source     :
    - https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-0.6.0.tar.gz : ab04a20832eed4312873fb25abaed7fe3040484e33a6a97ec33053ba37d1942c
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-click
    - python-openssl
    - python-pyscard
    - python-pyusb
    - python-setuptools
rundeps    :
    - ccid
    - libu2f-host
    - python-click
    - python-cryptography
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install
    install -d -m 00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../pcscd.socket $installdir/%libdir%/systemd/system/sockets.target.wants/pcscd.socket
    install -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../pcscd.service $installdir/%libdir%/systemd/system/multi-user.target.wants/pcscd.service
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
