name       : yubikey-manager
version    : 1.0.0
release    : 15
source     :
    - https://github.com/Yubico/yubikey-manager/archive/yubikey-manager-1.0.0.tar.gz : a6f049f0ed6f0bdb649ec12a478d95bdb8bf1101eb11ea87d449cdb803c83852
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-click
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - python-setuptools
    - python-testpath
rundeps    :
    - ccid
    - python-click
    - python-cryptography
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install

    install -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../pcscd.service $installdir/%libdir%/systemd/system/multi-user.target.wants/pcscd.service
