name       : yubikey-manager
version    : 0.3.1
release    : 1
source     :
    - https://github.com/Yubico/yubikey-manager/releases/download/yubikey-manager-0.3.1/yubikey-manager-0.3.1.tar.gz : cf60cbbfc12a331afe6e261e0294326ec18eeb43bba559049638308f1656306f
license    : BSD-2-Clause
component  : security
summary    : Python library and command line tool for configuring any YubiKey over all USB transports.
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - libu2f-host
    - python-click
    - python-cryptography
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install
