name       : yubikey-manager
version    : 2.0.0
release    : 17
source     :
    - https://github.com/Yubico/yubikey-manager/archive/yubikey-manager-2.0.0.tar.gz : cb402f66e738c3e7d9752b9916837382acff9ccd7ff4ecaa6ddd0231303d50dc
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-click
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - python-setuptools
    - python-testpath
rundeps    :
    - ccid
    - python-click
    - python-cryptography
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install

    install -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../pcscd.service $installdir/%libdir%/systemd/system/multi-user.target.wants/pcscd.service
