name       : yubikey-manager
version    : 4.0.3
release    : 27
source     :
    - https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-4.0.3.tar.gz : a7bb6ffdb8fa3cc0a7094e63f15862eb42f12e23e64750ae7fcc5574356d66f4
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
networking : yes
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-click
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - python-testpath
rundeps    :
    - ccid
    - python-click
    - python-cryptography
    - python-fido2
    - python-openssl
    - python-pyscard
build      : |
    %python3_setup
install    : |
    %python3_install

    # Vendor enable pcscd.socket so this works OOTB.
    install -dm00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../pcscd.socket $installdir/%libdir%/systemd/system/sockets.target.wants/pcscd.socket
