name       : yubikey-manager
version    : 0.4.5
release    : 5
source     :
    - https://github.com/Yubico/yubikey-manager/releases/download/yubikey-manager-0.4.5/yubikey-manager-0.4.5.tar.gz : d91f5b549b23bfc6c04d9446b9ced6c6f80aac702b26a1fa4d1b8df5eb9a36d8
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - ccid
    - libu2f-host
    - python-click
    - python-cryptography
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install
