name       : yubikey-manager
version    : 3.1.0
release    : 20
source     :
    - https://github.com/Yubico/yubikey-manager/archive/yubikey-manager-3.1.0.tar.gz : 9009ad6695b262c23abfb2d030786bcb5d72756f822ce74eb20d611a9cd130bd
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-click
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - python-setuptools
    - python-testpath
rundeps    :
    - ccid
    - python-click
    - python-cryptography
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install

    install -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../pcscd.service $installdir/%libdir%/systemd/system/multi-user.target.wants/pcscd.service
