name       : yubikey-manager
version    : 0.4.4
release    : 4
source     :
    - https://github.com/Yubico/yubikey-manager/releases/download/yubikey-manager-0.4.4/yubikey-manager-0.4.4.tar.gz : 65839d29205427b8e4ae0c358684a5880eb5a52caff50943a6ca9fdaa4f782fb
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
 Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - ccid
    - libu2f-host
    - python-click
    - python-cryptography
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install
