name       : yubikey-manager
version    : 5.1.1
release    : 35
source     :
    - https://github.com/Yubico/yubikey-manager/releases/download/5.1.1/yubikey_manager-5.1.1.tar.gz : 6487db976d8b5b52965db55d084f9d2aef2b96f77da785dc13f6dfdd3302aace
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
networking : yes
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-build
    - python-click
    - python-fido2
    - python-installer
    - python-openssl
    - python-packaging
    - python-pyscard
    - python-pyusb
    - python-testpath
    - python-wheel
rundeps    :
    - ccid
    - python-click
    - python-cryptography
    - python-fido2
    - python-openssl
    - python-pyscard
environment: |
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
setup      : |
    python3 -m pip install --user poetry
build      : |
    %python3_setup
install    : |
    %python3_install

    # Vendor enable pcscd.socket so this works OOTB.
    install -dm00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../pcscd.socket $installdir/%libdir%/systemd/system/sockets.target.wants/pcscd.socket
