name       : yubikey-manager
version    : 0.5.0
release    : 8
source     :
    - https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-0.5.0.tar.gz : c4a7c6f8af3c7f719a0c1dfcbe12440667c60137f74188ff8d4c5506bd631118
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-setuptools
rundeps    :
    - ccid
    - libu2f-host
    - python-click
    - python-cryptography
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install
    install -d -m 00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../pcscd.socket $installdir/%libdir%/systemd/system/sockets.target.wants/pcscd.socket
    install -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../pcscd.service $installdir/%libdir%/systemd/system/multi-user.target.wants/pcscd.service
