name       : yubikey-manager
version    : 0.6.1
release    : 10
source     :
    - https://github.com/Yubico/yubikey-manager/archive/yubikey-manager-0.6.1.tar.gz : 0629bca33f2a93952c074e87697c2bb3ada2627c43dc206ab6cb8b2949422ec2
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-click
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - python-setuptools
rundeps    :
    - ccid
    - python-click
    - python-cryptography
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install

    # Vendor enable required pcscd service
    install -d -m 00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../pcscd.socket $installdir/%libdir%/systemd/system/sockets.target.wants/pcscd.socket
    install -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../pcscd.service $installdir/%libdir%/systemd/system/multi-user.target.wants/pcscd.service
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
