name       : yubikey-manager
version    : 0.3.3
release    : 2
source     :
    - https://github.com/Yubico/yubikey-manager/releases/download/yubikey-manager-0.3.3/yubikey-manager-0.3.3.tar.gz : 5447c026739d33455ac8ae13ccaef2df231a28dda75ffbd62c91a7c5ce5d30b5
license    : BSD-2-Clause
component  : security
summary    : Python library and command line tool for configuring any YubiKey over all USB transports.
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - libu2f-host
    - python-click
    - python-cryptography
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install
