name       : yubikey-manager
version    : 3.1.1
release    : 23
source     :
    - https://github.com/Yubico/yubikey-manager/archive/yubikey-manager-3.1.1.tar.gz : de32cd8a6b1d30c038bdba806c1d0b9eb9b4540c789bb09b13e65f99f2d4c482
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-click
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - python-testpath
rundeps    :
    - ccid
    - python-click
    - python-cryptography
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install

    # Vendor enable pcscd.socket so this works mostly OOTB (requires reboot).
    install -dm00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../pcscd.socket $installdir/%libdir%/systemd/system/sockets.target.wants/pcscd.socket
