name       : yubikey-manager
version    : 4.0.1
release    : 25
source     :
    - https://github.com/Yubico/yubikey-manager/releases/download/4.0.1/yubikey-manager-4.0.1.tar.gz : 3b16caa39bf038169b53aff684ee113168a27e8e08548c73f8395cc0ff713bf1
license    : BSD-2-Clause
component  : security
summary    : Command line utility for configuring your YubiKey
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
networking : yes
builddeps  :
    - pkgconfig(python3)
    - pcsc-lite
    - python-click
    - python-fido2
    - python-openssl
    - python-pyscard
    - python-pyusb
    - python-testpath
rundeps    :
    - ccid
    - python-click
    - python-cryptography
    - python-fido2
    - python-openssl
    - python-pyscard
build      : |
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
    pip3 install --user poetry
    python3 -m pip wheel --no-deps .
install    : |
    unset PYTHONUSERBASE
    python3 -m pip install --root=%installroot% --no-deps *.whl

    # Vendor enable pcscd.socket so this works OOTB.
    install -dm00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../pcscd.socket $installdir/%libdir%/systemd/system/sockets.target.wants/pcscd.socket
