name       : yubikey-manager
version    : 0.4.0
release    : 3
source     :
    - https://github.com/Yubico/yubikey-manager/releases/download/yubikey-manager-0.4.0/yubikey-manager-0.4.0.tar.gz : ebe9b78522e66de65c0648662915d535a6beba7b2fd72c3480729a8c1eae8035
license    : BSD-2-Clause
component  : security
summary    : Python library and command line tool for configuring any YubiKey over all USB transports.
description: |
    Python library and command line tool for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - ccid
    - libu2f-host
    - python-click
    - python-cryptography
    - python-openssl
    - python-pyscard
    - python-pyusb
    - yubikey-personalization
build      : |
    %python3_setup
install    : |
    %python3_install
